# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dist_sgd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dist_sgd.proto',
  package='dist_sgd',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64ist_sgd.proto\x12\x08\x64ist_sgd\"Y\n\x06Params\x12\x12\n\ntensor_len\x18\x01 \x01(\x05\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x11\n\tdata_indx\x18\x03 \x01(\x05\x12\x15\n\tfloat_val\x18\x04 \x03(\x02\x42\x02\x10\x01\x32\x41\n\x0bParamFeeder\x12\x32\n\nSendParams\x12\x10.dist_sgd.Params\x1a\x10.dist_sgd.Params\"\x00\x42\x1e\n\x0bio.dist_sgdB\x07\x44istSGDP\x01\xa2\x02\x03\x44SGb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='dist_sgd.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tensor_len', full_name='dist_sgd.Params.tensor_len', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='dist_sgd.Params.client_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_indx', full_name='dist_sgd.Params.data_indx', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_val', full_name='dist_sgd.Params.float_val', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'dist_sgd_pb2'
  # @@protoc_insertion_point(class_scope:dist_sgd.Params)
  ))
_sym_db.RegisterMessage(Params)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\013io.dist_sgdB\007DistSGDP\001\242\002\003DSG'))
_PARAMS.fields_by_name['float_val'].has_options = True
_PARAMS.fields_by_name['float_val']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
import abc
from grpc.beta import implementations as beta_implementations
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

class BetaParamFeederServicer(object):
  """<fill me in later!>"""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SendParams(self, request, context):
    raise NotImplementedError()

class BetaParamFeederStub(object):
  """The interface to which stubs will conform."""
  __metaclass__ = abc.ABCMeta
  @abc.abstractmethod
  def SendParams(self, request, timeout):
    raise NotImplementedError()
  SendParams.future = None

def beta_create_ParamFeeder_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  import dist_sgd_pb2
  import dist_sgd_pb2
  request_deserializers = {
    ('dist_sgd.ParamFeeder', 'SendParams'): dist_sgd_pb2.Params.FromString,
  }
  response_serializers = {
    ('dist_sgd.ParamFeeder', 'SendParams'): dist_sgd_pb2.Params.SerializeToString,
  }
  method_implementations = {
    ('dist_sgd.ParamFeeder', 'SendParams'): face_utilities.unary_unary_inline(servicer.SendParams),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)

def beta_create_ParamFeeder_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  import dist_sgd_pb2
  import dist_sgd_pb2
  request_serializers = {
    ('dist_sgd.ParamFeeder', 'SendParams'): dist_sgd_pb2.Params.SerializeToString,
  }
  response_deserializers = {
    ('dist_sgd.ParamFeeder', 'SendParams'): dist_sgd_pb2.Params.FromString,
  }
  cardinalities = {
    'SendParams': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'dist_sgd.ParamFeeder', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
